# BCTC Annual PDF Manager

Notebook điều phối ingestion semi-structured (PDF-first) cho BCTC năm.

Luồng hiện tại chỉ 1 stage:
- Crawl danh sách công bố + download PDF + ghi metadata

Stage parse/OCR đã được loại bỏ khỏi flow này.

**Mặc định:** `hnx_verify_ssl=False` và `strict_bctc_annual_keyword_filter=False` — crawl `www.hnx.vn` và giữ mọi PDF để xem dữ liệu. Khi triển khai thật: bật `hnx_verify_ssl=True` (hoặc `HNX_SSL_VERIFY=1`) và có thể bật `strict_bctc_annual_keyword_filter=True` để chỉ BCTC năm.

**Số trang HNX:** code mặc định `hnx_max_list_pages=10` (DAG weekly). Notebook: `BCTC_RUN_PROFILE="backfill"` → **100** trang; `"dag_weekly"` → **10** (giống DAG, không cần set env).

In [1]:
import os
import sys
import warnings
import threading
from pathlib import Path

os.environ["PYTHONUTF8"] = "1"
os.environ["PYTHONIOENCODING"] = "utf-8"

# SSL www.hnx.vn: mac dinh code dung hnx_verify_ssl=False. Muon bat verify TLS:
#   trong .env dat HNX_SSL_VERIFY=1  hoac  SemiStructuredIngestionConfig(hnx_verify_ssl=True)

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

_orig_hook = threading.excepthook

def _quiet_hook(args):
    if "UnicodeDecodeError" in str(args.exc_type):
        return
    _orig_hook(args)

threading.excepthook = _quiet_hook
warnings.filterwarnings("ignore")

root = Path.cwd()
if not (root / "ingestion").is_dir():
    root = root.parent
if str(root) not in sys.path:
    sys.path.insert(0, str(root))

print("[OK] UTF-8 guard + sys.path ready")

[OK] UTF-8 guard + sys.path ready

In [ ]:
# backfill = lan dau / notebook: toi da 100 trang HNX (trang 1 = moi nhat)
# dag_weekly = giong mac dinh code (10 trang) — sau nay Airflow khong can set env
BCTC_RUN_PROFILE = "backfill"  # "backfill" | "dag_weekly"

_HNX_MAX_LIST_PAGES_BY_PROFILE = {
    "backfill": 100,
    "dag_weekly": 10,
}
if BCTC_RUN_PROFILE not in _HNX_MAX_LIST_PAGES_BY_PROFILE:
    raise ValueError(
        f"BCTC_RUN_PROFILE must be one of {list(_HNX_MAX_LIST_PAGES_BY_PROFILE)}, got {BCTC_RUN_PROFILE!r}"
    )
HNX_MAX_LIST_PAGES = _HNX_MAX_LIST_PAGES_BY_PROFILE[BCTC_RUN_PROFILE]
print(f"BCTC_RUN_PROFILE={BCTC_RUN_PROFILE} -> hnx_max_list_pages={HNX_MAX_LIST_PAGES}")

BCTC_RUN_PROFILE=backfill -> hnx_max_list_pages=500

In [3]:
import os

from ingestion.common import configure_logging, load_dotenv_from_project_root
from ingestion.semi_structure_data import (
    SemiStructuredIngestionConfig,
    run_bctc_annual_pipeline,
)

configure_logging()
load_dotenv_from_project_root()

if os.environ.get("HNX_SSL_VERIFY", "").strip().lower() in ("0", "false", "no"):
    print("[INFO] .env: HNX_SSL_VERIFY — tat verify SSL cho www.hnx.vn")


cfg = SemiStructuredIngestionConfig(
    sources=["hnx"],
    hnx_max_list_pages=HNX_MAX_LIST_PAGES,
    rate_limit_rpm=20,
    min_pdf_bytes=20_000,
    # Mac dinh trong config: hnx_verify_ssl=False, strict_bctc_annual_keyword_filter=False
    # de crawl duoc tren Windows va xem du lieu. Production: bat True + HNX_SSL_VERIFY=1.
)

print(f"run_date: {cfg.run_date}")
print(f"data_lake_root: {cfg.data_lake_root}")
print(f"hnx_max_list_pages (config): {cfg.hnx_max_list_pages}")
print(f"hnx_max_list_pages (resolved): {cfg.resolved_hnx_max_list_pages()}")

2026-06-03 10:06:54 [INFO] Đã nạp biến môi trường từ D:\WorkSpace\Đồ Án 2\stock-pipeline\.env

run_date: 2026-06-03
data_lake_root: D:\WorkSpace\Đồ Án 2\stock-pipeline\data-lake\raw
hnx_max_list_pages (config): 500
hnx_max_list_pages (resolved): 500

In [4]:
# Download-only — tự bootstrap nếu chưa chạy cell import/`cfg`.
from pathlib import Path
import sys

_root = Path.cwd()
if not (_root / "ingestion").is_dir():
    _root = _root.parent
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))

from ingestion.common import configure_logging, load_dotenv_from_project_root
from ingestion.semi_structure_data import SemiStructuredIngestionConfig, run_bctc_annual_pipeline

configure_logging()
load_dotenv_from_project_root()

if "cfg" not in globals():
    _pages = globals().get("HNX_MAX_LIST_PAGES", 100)
    cfg = SemiStructuredIngestionConfig(sources=["hnx"], hnx_max_list_pages=_pages)

out_download = run_bctc_annual_pipeline(
    cfg,
    include_download=True,
 )
out_download

2026-06-03 10:06:54 [INFO] Đã nạp biến môi trường từ D:\WorkSpace\Đồ Án 2\stock-pipeline\.env
2026-06-03 10:06:54 [INFO] hnx_verify_ssl=False (mac dinh dev) — tat SSL verify cho www.hnx.vn; dat hnx_verify_ssl=True hoac HNX_SSL_VERIFY=1 khi can an toan
2026-06-03 10:06:54 [INFO] HNX list crawl: max_pages=500 start_page=1 rate_limit_rpm=20
2026-06-03 10:09:31 [INFO] HNX attachment accepted: SJ1 | 1.SJ1_2026.6.2_22381fe_EN_Reviewed_Consolidate_halfyear_financial_statements_Signed.pdf
2026-06-03 10:09:31 [INFO] HNX attachment accepted: SJ1 | 2.SJ1_2026.6.2_3a6e14f_VI_BCTC_ban_nien_HN_Signed.pdf
2026-06-03 10:09:54 [INFO] HNX attachment accepted: SAF | 1.SAF_2026.6.2_f0184c3_VI_thongbaoCBTT.pdf
2026-06-03 10:10:01 [INFO] HNX attachment accepted: PIC | 1.PIC_2026.6.2_5432ae9_VI_CBTTkhac.pdf
2026-06-03 10:10:01 [INFO] HNX attachment accepted: PIC | 2.PIC_2026.6.2_740d1ac_EN_otherextraordinarydisclosure.pdf
2026-06-03 10:11:37 [INFO] HNX attachment accepted: V21 | 1.V21_2026.6.1_1da6ef5_VI_CBTTkhac.pdf
2026-06-03 10:11:37 [INFO] HNX attachment accepted: V21 | 2.V21_2026.6.1_6e01620_EN_otherextraordinarydisclosure.pdf
2026-06-03 10:12:37 [INFO] HNX attachment accepted: QHD | 1.QHD_2026.6.1_35f2ed2_VI_Cong_bo_thong_tin_HD_Kiem_Toan.pdf
2026-06-03 10:12:37 [INFO] HNX attachment accepted: QHD | 2.QHD_2026.6.1_8a61524_EN_DISCLOSURE_OF_AUDIT_CONTRACT_INFORMATION.pdf
2026-06-03 10:14:13 [INFO] HNX attachment accepted: POT | 2.POT_2026.5.29_2ca60ff_VI_HopDongKIemToan_SoatXetBCTC.pdf
2026-06-03 10:16:58 [INFO] HNX attachment accepted: IVS | 1.IVS_2026.5.28_b6a483d_CV_CBTT_Ky_hop_dong_kiem_toan_signed.pdf
2026-06-03 10:17:28 [INFO] HNX attachment accepted: KSD | 1.KSD_2026.5.28_ddd3a70_KSD_Ky_hd_kiem_toan_bao_cao_tai_chinh_ban_nien_va_nam_2026.pdf
2026-06-03 10:21:10 [INFO] HNX attachment accepted: IDJ | 1.IDJ_2026.5.27_3ef76db_VI_GiaiTrinhLienQuanDenBCTC_Q1_2026_Me.pdf
2026-06-03 10:21:10 [INFO] HNX attachment accepted: IDJ | 2.IDJ_2026.5.27_c73cbcb_VI_BaoCaoTaiChinh_Q1_2026_Me.pdf
2026-06-03 10:21:10 [INFO] HNX attachment accepted: IDJ | 3.IDJ_2026.5.27_cb73551_EN_ExplanationsRelatingToFSs_Q1_2026_Me.pdf
2026-06-03 10:21:10 [INFO] HNX attachment accepted: IDJ | 4.IDJ_2026.5.27_ded3476_EN_FinancialStatements_Q1_2026_Me.pdf
2026-06-03 10:22:22 [INFO] HNX attachment accepted: DDG | 1.DDG_2026.5.27_45ced22_EN_ConsolidatedFinancialStatements_Q1_.2026.pdf
2026-06-03 10:22:22 [INFO] HNX attachment accepted: DDG | 2.DDG_2026.5.27_5223691_VI_Baocaotaichinh_HN_Q1_.2025.pdf
2026-06-03 10:22:22 [INFO] HNX attachment accepted: DDG | 3.DDG_2026.5.27_5ae4d6f_VI_GiaiTrinhLienQuanDenBCTC_Q1_2026_01.pdf
2026-06-03 10:22:22 [INFO] HNX attachment accepted: DDG | 4.DDG_2026.5.27_be83133_EN_ExplanationsRelatingToFSs__Quarter_1_2026_02.pdf
2026-06-03 10:22:22 [INFO] HNX attachment accepted: DDG | 5.DDG_2026.5.27_df183d7_EN_ExplanationsRelatingToFSs__Quarter_1_2026_01.pdf
2026-06-03 10:22:22 [INFO] HNX attachment accepted: DDG | 6.DDG_2026.5.27_e1d8416_VI_GiaiTrinhLienQuanDenBCTC_Q1_2026_02.pdf
2026-06-03 10:22:28 [INFO] HNX attachment accepted: CMS | 1.CMS_2026.5.27_5a89b83_CBTT_17_EV.pdf
2026-06-03 10:22:28 [INFO] HNX attachment accepted: CMS | 2.CMS_2026.5.27_ae7a9c0_CBTT_17_VN.pdf
2026-06-03 10:22:31 [INFO] HNX attachment accepted: API | 1.API_2026.5.27_166b3e6_VI_GiaitrinhlienquandenBCTC_Q1_2026.pdf
2026-06-03 10:22:31 [INFO] HNX attachment accepted: API | 2.API_2026.5.27_5d4ca83_EN_ExplanationsRelatingtoFSs_Q1_2026.pdf
2026-06-03 10:22:31 [INFO] HNX attachment accepted: API | 3.API_2026.5.27_647f1ca_VI_BaoCaoTaiChinh_Hopnhat_Q1_2026.pdf
2026-06-03 10:22:31 [INFO] HNX attachment accepted: API | 4.API_2026.5.27_790b94e_EN_ConsolidatedFinancialStatements_Q1_2026.pdf
2026-06-03 10:22:34 [INFO] HNX attachment accepted: API | 1.API_2026.5.27_5c61a8c_EN_ExplanationsRelatingtoFSs_Q1_2026.pdf
2026-06-03 10:22:34 [INFO] HNX attachment accepted: API | 2.API_2026.5.27_6c6e372_VI_GiaitrinhlienquandenBCTC_Q1_2026.pdf
2026-06-03 10:22:34 [INFO] HNX attachment accepted: API | 3.API_2026.5.27_7a13f97_EN_FinancialStatements_Q1_2026.pdf
2026-06-03 10:22:34 [INFO] HNX attachment accepted: API | 4.API_2026.5.27_b22aa6e_VI_BaocaoTaiChinh_Rieng_Q1_2026.pdf
2026-06-03 10:22:40 [INFO] HNX attachment accepted: BKC | 1.BKC_2026.5.27_11fe51c_VI_BaoCaoTaiChinhRieng_Q1_2026.signed.pdf
2026-06-03 10:22:40 [INFO] HNX attachment accepted: BKC | 2.BKC_2026.5.27_22ed3bf_178._Giai_trinh_BCTC_rieng_quy_I_2026.bantienganh.signed.pdf
2026-06-03 10:22:40 [INFO] HNX attachment accepted: BKC | 3.BKC_2026.5.27_2b724b6_178._Giai_trinh_BCTC_Rieng_Quy_I_2026.signed.pdf
2026-06-03 10:22:40 [INFO] HNX attachment accepted: BKC | 4.BKC_2026.5.27_b29d164_EN_AuditedFinancialStatementsSeparate_Q1_2026.signed.pdf
2026-06-03 10:22:43 [INFO] HNX attachment accepted: BKC | 1.BKC_2026.5.27_2e475f0_VI_BaoCaoTaiChinhHopNhat_Q1_2026.signed.pdf
2026-06-03 10:22:43 [INFO] HNX attachment accepted: BKC | 2.BKC_2026.5.27_4466c58_EN_AuditedFinancialStatementsConsolidated_Q1_2026.signed.pdf
2026-06-03 10:22:43 [INFO] HNX attachment accepted: BKC | 3.BKC_2026.5.27_a0f8f2a_177._Giai_trinh_BCTC_hop_nhat_Quy_I_2026.signed.pdf
2026-06-03 10:22:43 [INFO] HNX attachment accepted: BKC | 4.BKC_2026.5.27_e508098_177.Giai__trinh_BCTC_hop_nhat_quy_I_2026.Bantienganh.signed.pdf
2026-06-03 10:23:16 [INFO] HNX attachment accepted: TKU | 1.TKU_2026.5.27_24a1aca_EN_otherextraordinarydisclosure.pdf
2026-06-03 10:23:16 [INFO] HNX attachment accepted: TKU | 2.TKU_2026.5.27_59767e0_VI_KY_HD_KIEM_TOAN.pdf
2026-06-03 10:25:32 [INFO] HNX attachment accepted: IDJ | 1.IDJ_2026.5.26_2a6c3f5_VI_GiaiTrinhLienQuanDenBCTC_Q1_2026_Hop_nhat.pdf
2026-06-03 10:25:32 [INFO] HNX attachment accepted: IDJ | 2.IDJ_2026.5.26_b5a8674_EN_FinancialStatements_Q1_2026_Hop_nhat.pdf
2026-06-03 10:25:32 [INFO] HNX attachment accepted: IDJ | 3.IDJ_2026.5.26_d224ce4_EN_ExplanationsRelatingToFSs_Q1_2026_Hop_nhat.pdf
2026-06-03 10:25:32 [INFO] HNX attachment accepted: IDJ | 4.IDJ_2026.5.26_f7d0872_VI_BaoCaoTaiChinh_Q1_2026_Hop_nhat.pdf
2026-06-03 10:28:53 [INFO] HNX attachment accepted: VGP | 1.VGP_2026.5.26_a76a9cf_VI_EI_CBTT_Bat_thuong_vv_Lua_chon_don_vu_kiem_toan_cho_Cong_ty_trong_nam_2026_signed.pdf
2026-06-03 10:29:02 [INFO] HNX attachment accepted: TIG | 1.TIG_2026.5.26_08312b5_EN_Explanation_relating_to_FS_Q1_2026.pdf
2026-06-03 10:29:02 [INFO] HNX attachment accepted: TIG | 2.TIG_2026.5.26_38a2fcd_VI_BCTC_hop_nhat_TIG_Q1.2026.pdf
2026-06-03 10:29:02 [INFO] HNX attachment accepted: TIG | 3.TIG_2026.5.26_452dbca_EN_Disclosure_Financial_Statements_Q1.2026_TIG.pdf
2026-06-03 10:29:02 [INFO] HNX attachment accepted: TIG | 4.TIG_2026.5.26_ac814e9_VI_Giai_trinh_lien_quan_den_BCTC_Q1.2026.pdf
2026-06-03 10:29:02 [INFO] HNX attachment accepted: TIG | 5.TIG_2026.5.26_c895851_EN_Consolidated_Financial_Statements_TIG_Q1.2026.pdf
2026-06-03 10:29:02 [INFO] HNX attachment accepted: TIG | 6.TIG_2026.5.26_f504dfe_VI_CBTT_BCTC_Q1.2026__TIG.pdf
2026-06-03 10:29:05 [INFO] HNX attachment accepted: TIG | 1.TIG_2026.5.26_004e919_VI_BCTC_rieng_Q1.2026_TIG.pdf
2026-06-03 10:29:05 [INFO] HNX attachment accepted: TIG | 2.TIG_2026.5.26_15af0da_EN_Explanation_relating_to_FS_Q1_2026.pdf
2026-06-03 10:29:05 [INFO] HNX attachment accepted: TIG | 3.TIG_2026.5.26_5248152_EN_Disclosure_Financial_Statements_Q1.2026_TIG.pdf
2026-06-03 10:29:05 [INFO] HNX attachment accepted: TIG | 4.TIG_2026.5.26_d3cb8c8_EN_Separate_Financial_Statements_Q1.2026_TIG.pdf
2026-06-03 10:29:05 [INFO] HNX attachment accepted: TIG | 5.TIG_2026.5.26_f5d80ed_VI_Giai_trinh_lien_quan_den_BCTC_Q1.2026.pdf
2026-06-03 10:29:05 [INFO] HNX attachment accepted: TIG | 6.TIG_2026.5.26_f9e80cd_VI_CBTT_BCTC_Q1.2026__TIG.pdf
2026-06-03 10:29:08 [INFO] HNX attachment accepted: SCG | 1.SCG_2026.5.26_0f9ad69_VI_BaoCaoTaiChinhHN_QI_2026.pdf
2026-06-03 10:29:08 [INFO] HNX attachment accepted: SCG | 2.SCG_2026.5.26_9dead3a_EN_ExplanationsRelatingToFSs_QI_2026.pdf
2026-06-03 10:29:08 [INFO] HNX attachment accepted: SCG | 3.SCG_2026.5.26_c14ca6d_EN_ConsolidatedFinancialStatements_QI_2026.pdf
2026-06-03 10:29:08 [INFO] HNX attachment accepted: SCG | 4.SCG_2026.5.26_d592aa9_Cong_van_cong_bo_thong_tin_dinh_ky_bao_cao_tai_chinh.dks.pdf
2026-06-03 10:29:08 [INFO] HNX attachment accepted: SCG | 5.SCG_2026.5.26_d6e6ce5_VI_GiaiTrinhLienQuanDenBCTC_QI_2026.pdf
2026-06-03 10:29:11 [INFO] HNX attachment accepted: SCG | 1.SCG_2026.5.26_12bbadc_Cong_van_cong_bo_thong_tin_dinh_ky_bao_cao_tai_chinh.dks.pdf
2026-06-03 10:29:11 [INFO] HNX attachment accepted: SCG | 2.SCG_2026.5.26_1f34b7a_VI_BaoCaoTaiChinh_QI_2026.pdf
2026-06-03 10:29:11 [INFO] HNX attachment accepted: SCG | 3.SCG_2026.5.26_99371f9_EN_ExplanationsRelatingToFSs_QI_2026.pdf
2026-06-03 10:29:11 [INFO] HNX attachment accepted: SCG | 4.SCG_2026.5.26_b7e75e7_VI_GiaiTrinhLienQuanDenBCTC_QI_2026.pdf
2026-06-03 10:29:11 [INFO] HNX attachment accepted: SCG | 5.SCG_2026.5.26_e85756b_EN_FinancialStatements_QI_2026.pdf
2026-06-03 10:29:20 [INFO] HNX attachment accepted: TTT | 1.TTT_2026.5.26_3b4d7cd_EN_FinacialStatements_HN_Q1_2026.pdf
2026-06-03 10:29:20 [INFO] HNX attachment accepted: TTT | 2.TTT_2026.5.26_acb06d0_VI_BaoCaoTaiChinh_HN_Q1_2026.pdf
2026-06-03 10:29:23 [INFO] HNX attachment accepted: TTT | 1.TTT_2026.5.26_5213656_VI_BaoCaoTaiChinh_Q1_2026.pdf
2026-06-03 10:29:23 [INFO] HNX attachment accepted: TTT | 2.TTT_2026.5.26_d153c91_EN_FinacialStatements_Q1_2026.pdf
2026-06-03 10:31:35 [INFO] HNX attachment accepted: CSC | 1.CSC_2026.5.25_09a3c5f_1._VI_BCTC_ME_RIENG_QUY_1.2026.signed.pdf
2026-06-03 10:31:35 [INFO] HNX attachment accepted: CSC | 2.CSC_2026.5.25_18b55ad_2._EN_BCTC_ME_RIENG_QUY_1.2026.signed.pdf
2026-06-03 10:31:38 [INFO] HNX attachment accepted: CSC | 1.CSC_2026.5.25_093dd48_CBTT_BAO_CAO_TAI_CHINH_QUY_1.2026.signed.pdf
2026-06-03 10:31:38 [INFO] HNX attachment accepted: CSC | 2.CSC_2026.5.25_30d0fe8_2._EN_BCTC_HOP_NHAT_QUY_1.2026.signed.pdf
2026-06-03 10:31:38 [INFO] HNX attachment accepted: CSC | 3.CSC_2026.5.25_8e701e2_1._VI__BCTC_HOP_NHAT_QUY_1.2026.signed.pdf
2026-06-03 10:31:44 [INFO] HNX attachment accepted: AMV | 1.AMV_2026.5.25_f7ee9d3_VI_CBTTkhac.pdf
2026-06-03 10:31:44 [INFO] HNX attachment accepted: AMV | 2.AMV_2026.5.25_fbeadbc_EN_otherextraordinarydisclosure.pdf
2026-06-03 10:32:11 [INFO] HNX attachment accepted: DDG | 1.DDG_2026.5.25_0dc8c03_VI_GiaiTrinhLienQuanDenBCTC_Q1_2026_01.pdf
2026-06-03 10:32:11 [INFO] HNX attachment accepted: DDG | 2.DDG_2026.5.25_2617e06_VI_Baocaotaichinhrieng_Q1_.2026.pdf
2026-06-03 10:32:11 [INFO] HNX attachment accepted: DDG | 3.DDG_2026.5.25_288257a_VI_GiaiTrinhLienQuanDenBCTC_Q1_2026_02.pdf
2026-06-03 10:32:11 [INFO] HNX attachment accepted: DDG | 4.DDG_2026.5.25_6fcbaf7_EN_ExplanationsRelatingToFSs__Quarter_1_2026_01.pdf
2026-06-03 10:32:11 [INFO] HNX attachment accepted: DDG | 5.DDG_2026.5.25_8ac4f41_EN_SeparateFinancialStatements_Q1_.2026.pdf
2026-06-03 10:32:11 [INFO] HNX attachment accepted: DDG | 6.DDG_2026.5.25_d01f23d_EN_ExplanationsRelatingToFSs__Quarter_1_2026_02.pdf
2026-06-03 10:32:29 [INFO] HNX attachment accepted: CMS | 1.CMS_2026.5.25_ab84690_0_CBTT_BCTC_EN.pdf
2026-06-03 10:32:29 [INFO] HNX attachment accepted: CMS | 2.CMS_2026.5.25_be805cb_EN_ExplanationsRelatingToFSs_Quy_1.2026.pdf
2026-06-03 10:32:29 [INFO] HNX attachment accepted: CMS | 3.CMS_2026.5.25_d56112b_ENFinancialStatements_Quy_1.2026.pdf
2026-06-03 10:32:29 [INFO] HNX attachment accepted: CMS | 4.CMS_2026.5.25_d95fa13_VIBaoCaoTaiChinh_Quy_1.2026.pdf
2026-06-03 10:32:29 [INFO] HNX attachment accepted: CMS | 5.CMS_2026.5.25_e485c2c_VIGiaiTrinhLienQuanDenBCTC_Quy_1.2026.pdf
2026-06-03 10:32:29 [INFO] HNX attachment accepted: CMS | 6.CMS_2026.5.25_f255fb6_0_CBTT_BCTC_VN.pdf
2026-06-03 10:32:32 [INFO] HNX attachment accepted: CMS | 1.CMS_2026.5.25_1060b6e_EN_ExplanationsRelatingToFSs_Quy_1.2026.pdf
2026-06-03 10:32:32 [INFO] HNX attachment accepted: CMS | 2.CMS_2026.5.25_3f75af1_0_CBTT_BCTC_EN.pdf
2026-06-03 10:32:32 [INFO] HNX attachment accepted: CMS | 3.CMS_2026.5.25_b2df457_VIBaoCaoTaiChinhHopNhat_Quy_1.2026.pdf
2026-06-03 10:32:32 [INFO] HNX attachment accepted: CMS | 4.CMS_2026.5.25_ca11b3e_ENConsolidatedFinancialStatements_Quy_I.2026.pdf
2026-06-03 10:32:32 [INFO] HNX attachment accepted: CMS | 5.CMS_2026.5.25_cb53bad_VIGiaiTrinhLienQuanDenBCTC_Quy_1.2026.pdf
2026-06-03 10:32:32 [INFO] HNX attachment accepted: CMS | 6.CMS_2026.5.25_d49e6a2_0_CBTT_BCTC_VN.pdf
2026-06-03 10:32:41 [INFO] HNX attachment accepted: AMV | 1.AMV_2026.5.25_35e146f_TV._Giai_trinh_chenh_lech_loi_nhuan_BCTC_quy_1.pdf
2026-06-03 10:32:41 [INFO] HNX attachment accepted: AMV | 2.AMV_2026.5.25_915db57_TA._Giai_trinh_chenh_lech_loi_nhuan_BCTC_quy_1.pdf
2026-06-03 10:32:41 [INFO] HNX attachment accepted: AMV | 3.AMV_2026.5.25_c4030d7_AMV_TV._BCTC_Me_quy_1_nam_2026.pdf
2026-06-03 10:32:41 [INFO] HNX attachment accepted: AMV | 4.AMV_2026.5.25_d7eb3cf_AMV_TA._BCTC_Me_Quy_1_nam_2026.pdf
2026-06-03 10:32:50 [INFO] HNX attachment accepted: AMV | 1.AMV_2026.5.25_0d43336_EN_BCTC_HN_quy_1_nam_2026.pdf.pdf
2026-06-03 10:32:50 [INFO] HNX attachment accepted: AMV | 2.AMV_2026.5.25_b068b39_VI_BCTC_HN_quy_1_nam_2026.pdf.pdf
2026-06-03 10:32:50 [INFO] HNX attachment accepted: AMV | 3.AMV_2026.5.25_d465a31_TV._Giai_trinh_chenh_lech_loi_nhuan_BCTC_quy_1.pdf
2026-06-03 10:32:50 [INFO] HNX attachment accepted: AMV | 4.AMV_2026.5.25_df5c4b5_TA._Giai_trinh_chenh_lech_loi_nhuan_BCTC_quy_1.pdf
2026-06-03 10:33:17 [INFO] HNX attachment accepted: TVC | 1.TVC_2026.5.25_9a317c5_VI_BaoCaoTaiChinhRieng_Q1_2026_signed.pdf
2026-06-03 10:33:17 [INFO] HNX attachment accepted: TVC | 2.TVC_2026.5.25_cbc9521_EN_TheSeparateFinancialStatements_Q1_2026_signed.pdf
2026-06-03 10:33:44 [INFO] HNX attachment accepted: PDB | 1.PDB_2026.5.25_7bd0201_EN_ExplanationsRelatingToFSs_GR_Q1_2026.pdf
2026-06-03 10:33:44 [INFO] HNX attachment accepted: PDB | 2.PDB_2026.5.25_8b323cb_VI_GiaiTrinhLienQuanDenBCTC_HN_Q1_2026.pdf
2026-06-03 10:33:44 [INFO] HNX attachment accepted: PDB | 3.PDB_2026.5.25_c113471_VI_BaoCaoTaiChinh__HN_Q1_2026.pdf
2026-06-03 10:33:44 [INFO] HNX attachment accepted: PDB | 4.PDB_2026.5.25_cfcffd7_EN_FinancialStatements_GR_Q1_2026.pdf
2026-06-03 10:33:47 [INFO] HNX attachment accepted: PDB | 1.PDB_2026.5.25_a2d1295_EN_FinancialStatements_PR_Q1_2026.pdf
2026-06-03 10:33:47 [INFO] HNX attachment accepted: PDB | 2.PDB_2026.5.25_e1b5477_VI_BaoCaoTaiChinh_ME_Q1_2026.pdf
2026-06-03 10:34:11 [INFO] HNX attachment accepted: MAS | 1.MAS_2026.5.25_03c51a9_CBTT_BCTC_Qui_12026.pdf
2026-06-03 10:34:11 [INFO] HNX attachment accepted: MAS | 2.MAS_2026.5.25_8024c83_EN_Financial_Report.Q1.26.pdf
2026-06-03 10:34:11 [INFO] HNX attachment accepted: MAS | 3.MAS_2026.5.25_c2c4333_VN_BCTC_quy_1.26.pdf
2026-06-03 10:34:11 [INFO] HNX attachment accepted: MAS | 4.MAS_2026.5.25_efabd73_Giai_trinh_LN_quy_I_2026.pdf
2026-06-03 10:34:41 [INFO] HNX attachment accepted: DNC | 1.DNC_2026.5.25_d624576_CBTT_HD_kiem_toan_2026_da_ky_so.pdf
2026-06-03 10:35:56 [INFO] HNX attachment accepted: HGM | 1.HGM_2026.5.22_e7ce86a_09.CBTT.HGMSigned.pdf
2026-06-03 10:37:41 [INFO] HNX attachment accepted: TMB | 1.TMB_2026.5.22_35ea072_EN.First_Quarter_2026_Financial_Report.pdf
2026-06-03 10:37:41 [INFO] HNX attachment accepted: TMB | 2.TMB_2026.5.22_66568f6_EN.Explanation_of_aftertax_profit_for_the_first_quarter_of_2026.pdf
2026-06-03 10:37:41 [INFO] HNX attachment accepted: TMB | 3.TMB_2026.5.22_c28458e_VN.BaoCaoTaiChinhQuy1Nam2026.pdf
2026-06-03 10:37:41 [INFO] HNX attachment accepted: TMB | 4.TMB_2026.5.22_f2b491e_VN.giai_trinh_loi_nhuan_sau_thue_quy_I_nam_2026.pdf
2026-06-03 10:37:53 [INFO] HNX attachment accepted: VE1 | 1.VE1_2026.5.22_3ceaf27_VI_BaoCaoTaiChinh_Q1_2026.pdf
2026-06-03 10:37:53 [INFO] HNX attachment accepted: VE1 | 2.VE1_2026.5.22_5c3da6f_Cong_van_so_37.pdf
2026-06-03 10:37:53 [INFO] HNX attachment accepted: VE1 | 3.VE1_2026.5.22_f8af0c5_EN_FinancialStatements_Q1_2026_18.pdf
2026-06-03 10:41:54 [INFO] HNX attachment accepted: KMT | 1.KMT_2026.5.20_87b4d8a_VI_CBTTkhac.pdf
2026-06-03 10:41:54 [INFO] HNX attachment accepted: KMT | 2.KMT_2026.5.20_922ac8d_EN_otherextraordinarydisclosure.pdf
2026-06-03 10:42:27 [INFO] HNX attachment accepted: SRA | 1.SRA_2026.5.20_0064f6f_EN._Bao_cao_tai_chinh_nam_2025.pdf
2026-06-03 10:42:27 [INFO] HNX attachment accepted: SRA | 2.SRA_2026.5.20_9fbb791_Giai_trinh_chenh_lech_BCTC_nam_2025.pdf
2026-06-03 10:42:27 [INFO] HNX attachment accepted: SRA | 3.SRA_2026.5.20_b98a46d_VI._Bao_cao_tai_chinh_nam_2025.pdf
2026-06-03 10:42:36 [INFO] HNX attachment accepted: SRA | 1.SRA_2026.5.20_4b8bc50_VI._Bao_cao_tai_chinh_nam_2025_cua_Cong_ty_me.pdf
2026-06-03 10:42:36 [INFO] HNX attachment accepted: SRA | 2.SRA_2026.5.20_7924374_EN._Bao_cao_tai_chinh_nam_2025_cua_Cong_ty_me.pdf
2026-06-03 10:42:36 [INFO] HNX attachment accepted: SRA | 3.SRA_2026.5.20_bab01ab_Giai_trinh_chenh_lech_BCTC_nam_2025_Cong_ty_me.pdf
2026-06-03 10:42:51 [INFO] HNX attachment accepted: FID | 1.FID_2026.5.20_571ceba_EN_Separate_financial_statements_Q1_2026.pdf
2026-06-03 10:42:51 [INFO] HNX attachment accepted: FID | 2.FID_2026.5.20_d10753a_EN_Explanation_regarding_the_separate_financial_statements_Q1_2026.pdf
2026-06-03 10:42:51 [INFO] HNX attachment accepted: FID | 3.FID_2026.5.20_df90df1_VN_Baocaotaichinhrieng_Q1_2026.pdf
2026-06-03 10:42:51 [INFO] HNX attachment accepted: FID | 4.FID_2026.5.20_e4b3c7d_VN_GiaitrinhlienquandenBCTCrieng_Q1_2026.pdf
2026-06-03 10:43:21 [INFO] HNX attachment accepted: C69 | 1.C69_2026.5.20_398f2ca_KS.Separate_Financial_Statements_Q1.2026.pdf
2026-06-03 10:43:21 [INFO] HNX attachment accepted: C69 | 2.C69_2026.5.20_4adcdcb_KS.CVGT_TH.pdf
2026-06-03 10:43:21 [INFO] HNX attachment accepted: C69 | 3.C69_2026.5.20_b428175_KS.Bao_cao_tai_chinh_me_quy_1.2026.pdf
2026-06-03 10:43:39 [INFO] HNX attachment accepted: DHP | 1.DHP_2026.5.20_15b4442_20_5_2026_DHP_CBTT_ve_viec_ky_HD_kiem_toan_voi_Cong_ty_TNHH_Kiem_toan_VACO_signed.pdf
2026-06-03 10:44:33 [INFO] HNX attachment accepted: HEV | 1.HEV_2026.5.19_1d55cef_VI_BaoCaoTaiChinh_Q1_2026TT99.final.sign.pdf
2026-06-03 10:44:33 [INFO] HNX attachment accepted: HEV | 2.HEV_2026.5.19_7e53be9_EN_FinancialStatements_Q1_2026TT99.final.sign.pdf
2026-06-03 10:44:33 [INFO] HNX attachment accepted: HEV | 3.HEV_2026.5.19_b3c40ec_EN_VN_GiatrinhlienquandenBCTC_Q1_26.sign.pdf
2026-06-03 10:45:03 [INFO] HNX attachment accepted: MEL | 1.MEL_2026.5.19_def3b56_HD_Kiem_toan_2026.pdf
2026-06-03 10:45:04 [INFO] HNX attachment accepted: MEL | 2.MEL_2026.5.19_e18282e_HD_Kiem_toan_2026_Eng.pdf
2026-06-03 10:45:36 [INFO] HNX attachment accepted: PRE | 1.PRE_2026.5.19_06360d3_Vn_BaoCaoTaiChinh_Q1_2026.pdf
2026-06-03 10:45:36 [INFO] HNX attachment accepted: PRE | 2.PRE_2026.5.19_a97c68f_EN_FinancialStatements_Q1_2026.pdf
2026-06-03 10:46:03 [INFO] HNX attachment accepted: CAN | 1.CAN_2026.5.19_3081209_Vi_GiaiTrinhLienQuanDenBCTC_2025_signed.pdf
2026-06-03 10:46:03 [INFO] HNX attachment accepted: CAN | 2.CAN_2026.5.19_485bf98_En_ExplanationsRelatingToFSs_2025_signed.pdf
2026-06-03 10:46:03 [INFO] HNX attachment accepted: CAN | 3.CAN_2026.5.19_52dcece_Vi_BaoCaoTaiChinh_HopNhat_2025_signed.pdf
2026-06-03 10:46:03 [INFO] HNX attachment accepted: CAN | 4.CAN_2026.5.19_678de9d_CBTT_BCTC_nam_2025_theo_mau_signed.pdf
2026-06-03 10:46:03 [INFO] HNX attachment accepted: CAN | 5.CAN_2026.5.19_d7f49e3_En_FinancialStatements_Consolidated_2025_signed.pdf
2026-06-03 10:46:09 [INFO] HNX attachment accepted: CAN | 1.CAN_2026.5.19_3d19a61_CBTT_BCTC_nam_2025_theo_mau_signed.pdf
2026-06-03 10:46:09 [INFO] HNX attachment accepted: CAN | 2.CAN_2026.5.19_775864a_En_FinancialStatements_Parent_2025_signed.pdf
2026-06-03 10:46:09 [INFO] HNX attachment accepted: CAN | 3.CAN_2026.5.19_eb73bf6_Vi_GiaiTrinhLienQuanDenBCTC_2025_signed.pdf
2026-06-03 10:46:09 [INFO] HNX attachment accepted: CAN | 4.CAN_2026.5.19_ed36875_En_ExplanationsRelatingToFSs_2025_signed.pdf
2026-06-03 10:46:09 [INFO] HNX attachment accepted: CAN | 5.CAN_2026.5.19_f5788ec_Vi_BaoCaoTaiChinh_CtyMe_2025_signed.pdf

{'run_date': '2026-06-03',
 'download': {'run_date': '2026-06-03',
  'documents_crawled': 1867,
  'download_ok': 1183,
  'download_fail': 0,
  'download_skipped_filter': 684,
  'metadata_parquet': 'D:\\WorkSpace\\Đồ Án 2\\stock-pipeline\\data-lake\\raw\\Semi_Structure_Data\\bctc_annual_pdf_meta\\source=hnx\\date=2026-06-03\\PART-000.parquet',
  'bootstrap_markers': ['D:\\WorkSpace\\Đồ Án 2\\stock-pipeline\\data-lake\\raw\\Semi_Structure_Data\\bctc_annual_pdf\\source=hnx\\_full_bootstrap_done.json']}}

In [5]:
# Tổng quan dữ liệu đã tải (theo ticker)
from pathlib import Path
import pandas as pd

def _human_bytes(num: int) -> str:
    num = int(num or 0)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if num < 1024:
            return f"{num:.1f} {unit}" if unit != "B" else f"{num} {unit}"
        num /= 1024
    return f"{num:.1f} PB"

def _load_metadata_df() -> pd.DataFrame:
    if "out_download" in globals() and isinstance(out_download, dict):
        meta_path = out_download.get("metadata_parquet")
        if meta_path:
            p = Path(meta_path)
            if p.is_file():
                return pd.read_parquet(p)
    if "cfg" in globals():
        meta_root = cfg.bctc_pdf_meta_root / "source=hnx"
        if meta_root.is_dir():
            date_dirs = sorted([p for p in meta_root.iterdir() if p.is_dir()])
            if date_dirs:
                p = date_dirs[-1] / "PART-000.parquet"
                if p.is_file():
                    return pd.read_parquet(p)
    return pd.DataFrame()

df = _load_metadata_df()
if df.empty:
    print("Chưa tìm thấy metadata Parquet. Hãy chạy cell download trước.")
else:
    df["file_size"] = df["file_size"].fillna(0).astype(int)
    downloaded = df[df["status"] == "downloaded"].copy()
    if downloaded.empty:
        print("Không có file nào trạng thái 'downloaded' trong metadata.")
    else:
        summary = (
            downloaded.groupby("ticker", dropna=False)
            .agg(files=("pdf_path", "count"), total_bytes=("file_size", "sum"))
            .reset_index()
        )
        summary["total_size"] = summary["total_bytes"].apply(_human_bytes)
        summary = summary.sort_values(["total_bytes", "files"], ascending=False)
        display(summary)

        total_files = int(summary["files"].sum())
        total_bytes = int(summary["total_bytes"].sum())
        print(
            f"Tổng tickers: {summary.shape[0]} | Tổng files: {total_files} | "
            f"Tổng dung lượng: {_human_bytes(total_bytes)}"
        )

    status_counts = df["status"].value_counts(dropna=False)
    display(status_counts.rename_axis("status").reset_index(name="count"))

    ticker  files  total_bytes total_size
45     DDG     25    177092703   168.9 MB
5      API     18    175247325   167.1 MB
48     DNP     12    168420844   160.6 MB
55     FID     11    163148751   155.6 MB
19     C69     10    161895935   154.4 MB
..     ...    ...          ...        ...
107    PMC      2      4806716     4.6 MB
109    PPE      2      2123064     2.0 MB
77     KSD      1       680247   664.3 KB
149    TKU      1       525299   513.0 KB
99     NTH      1       499131   487.4 KB

[189 rows x 4 columns]

Tổng tickers: 189 | Tổng files: 1183 | Tổng dung lượng: 8.1 GB

                  status  count
0             downloaded   1183
1  skipped_ingest_filter    684